[project]
name = "shllm"
version = "0.0.5"
description = "Natural langauge shell commands."
authors = [
    {name = "Ryan Hendry", email = "ryanhendry123@gmail.com"},
]
readme = "README.md"
requires-python = ">=3.11"

[project.scripts]
shllm = "shllm:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
